pipeline {
  
  agent {
    docker {image 'node:16-alpine'}
  }

  stages {
    
    stage("Test") {
      
      steps {
        
        echo 'testing the application'
        sh 'node --version'
        
      }
      
    }
    
  }
  
}
